# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
theme                    : jekyll-theme-modernist
locale                   : "en-US"
title                    : "Naifeng Fu/SHAO"
title_separator          : "-"
name                     : &name "Naifeng Fu"
description              : &description "Ph.D. candidate, Astromtry and Celestial Mechanics, Shanghai Astronomical Observatory, Chinese Academy of Sciences."
url                      : https://niphy.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "niphy/niphy.github.io"

# Site Author
author:
  name             : "Naifeng Fu"
  avatar           : "Me.png"
  bio              : "Ph.D. candidate, Astronomy and Celestial Mechanics, Shanghai Astronomical Observatory, Chinese Academy of Sciences."
  location         : "Nandan Road #80,\nShanghai, China"
  employer         :
  pubmed           : 
  googlescholar    : 
  email            : "mapoet.niphy@gmail.com"
  researchgate     :  
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "mapoet"
  google_plus      :
  keybase          :
  instagram        : "mapoet2"
  impactstory      : #"https://profiles.impactstory.org/u/xxxx-xxxx-xxxx-xxxx"
  lastfm           :
  linkedin         :
  orcid            : "http://orcid.org/yourorcidurl"
  pinterest        :
  soundcloud       :
  stackoverflow    : # http://stackoverflow.com/users/123456/username
  steam            :
  tumblr           :
  twitter          : "replacethistwitterhandle"
  vine             :
  weibo            : "https://weibo.com/2035075984"
  xing             :
  youtube          :
  wikipedia        :

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

compress_html:
  clippings: all
  ignore:
    envs: development
